CREATE OR REPLACE PROCEDURE show_parameters
IS
BEGIN
   IF $$PLSQL_DEBUG  THEN
      DBMS_OUTPUT.PUT_LINE ('DEBUG ON');
   ELSE
      DBMS_OUTPUT.PUT_LINE ('DEBUG OFF');
   END IF;
   DBMS_OUTPUT.PUT_LINE ($$PLSQL_OPTIMIZE_LEVEL);
   DBMS_OUTPUT.PUT_LINE ($$PLSQL_CODE_TYPE);
   DBMS_OUTPUT.PUT_LINE ($$PLSQL_WARNINGS);
   DBMS_OUTPUT.PUT_LINE ($$NLS_LENGTH_SEMANTICS);
END show_parameters;
/